const ImportErrorCodes = {
  CSV_PARSE_ERROR: 'CSV_PARSE_ERROR',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_ENUM_VALUE: 'INVALID_ENUM_VALUE',
  COMPANY_INACTIVE: 'COMPANY_INACTIVE',
  NUMBER_CONFLICT: 'NUMBER_CONFLICT',
  NUMBER_ARCHIVED: 'NUMBER_ARCHIVED',
  FK_NOT_FOUND: 'FK_NOT_FOUND',
};

module.exports = { ImportErrorCodes };

